In [3]:
path_to_zip_file = "DC_Properties.csv.zip"
directory_to_extract_to = ""

import zipfile
zip_ref = zipfile.ZipFile(path_to_zip_file,'r')
zip_ref.extractall(directory_to_extract_to)
zip_ref.close()

In [34]:
import pandas as pd

df = pd.read_csv("DC_Properties.csv")

df

C:\Users\Michel-Ange\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
5,5,3,2,Hot Water Rad,Y,1.0,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
6,6,1,0,Warm Cool,Y,2.0,5,2,1917.0,1988.0,...,-77.041055,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,7,3,1,Hot Water Rad,Y,2.0,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,8,3,1,Warm Cool,Y,2.0,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,9,1,1,Hot Water Rad,Y,1.0,6,2,1908.0,1979.0,...,-77.040081,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
11,11,5,0,Hot Water Rad,Y,3.0,16,6,1905.0,NaN,...,-77.039718,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
14,14,3,1,Warm Cool,Y,2.0,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
16,16,3,1,Warm Cool,Y,1.0,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
17,17,2,0,Hot Water Rad,N,1.0,6,3,1908.0,1987.0,...,-77.039961,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
18,18,3,1,Hot Water Rad,Y,2.0,10,4,1908.0,2006.0,...,-77.040020,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
19,19,3,1,Hot Water Rad,Y,2.0,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
20,20,3,1,Hot Water Rad,Y,1.0,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
21,21,3,0,Forced Air,Y,2.0,12,3,1880.0,2009.0,...,-77.033838,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
22,22,1,0,Forced Air,Y,1.0,6,3,1880.0,2010.0,...,-77.033925,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
23,23,2,1,Forced Air,Y,1.0,5,3,1880.0,2010.0,...,-77.033972,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
24,24,2,1,Hot Water Rad,Y,1.0,8,3,1880.0,2004.0,...,-77.034070,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
25,25,1,0,Hot Water Rad,N,1.0,8,4,1880.0,2010.0,...,-77.034156,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
27,27,3,0,Hot Water Rad,Y,4.0,9,3,1900.0,1963.0,...,-77.034182,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
28,28,3,0,Warm Cool,Y,2.0,10,4,1900.0,1960.0,...,-77.034119,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
29,29,3,1,Forced Air,Y,2.0,11,3,1900.0,2014.0,...,-77.034051,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158927,158927,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158928,158928,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158929,158929,2,1,Ht Pump,Y,NaN,5,2,2013.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158930,158930,2,0,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158931,158931,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158932,158932,2,1,Forced Air,N,NaN,4,2,1900.0,2003.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158933,158933,2,0,Ht Pump,Y,NaN,4,2,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158934,158934,1,1,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158935,158935,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158936,158936,1,0,Ht Pump,Y,NaN,3,1,1880.0,2016.0,...,-77.019243,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,476,-77.019245,38.912954,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158938,158938,2,0,Warm Cool,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158939,158939,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158940,158940,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158943,158943,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158944,158944,2,1,Forced Air,Y,NaN,5,2,2004.0,2004.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158945,158945,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158946,158946,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158947,158947,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158948,158948,2,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158949,158949,1,1,Forced Air,Y,NaN,4,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158950,158950,3,0,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158951,158951,3,1,Forced Air,Y,NaN,5,3,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158952,158952,1,0,Forced Air,Y,NaN,3,1,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158953,158953,1,0,Forced Air,Y,NaN,4,2,1938.0,2006.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.018230,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [35]:
# Show duplicates
dupe = df.loc[df.duplicated()]

dupe

Empty DataFrame
Columns: [Unnamed: 0, BATHRM, HF_BATHRM, HEAT, AC, NUM_UNITS, ROOMS, BEDRM, AYB, YR_RMDL, EYB, STORIES, SALEDATE, PRICE, QUALIFIED, SALE_NUM, GBA, BLDG_NUM, STYLE, STRUCT, GRADE, CNDTN, EXTWALL, ROOF, INTWALL, KITCHENS, FIREPLACES, USECODE, LANDAREA, GIS_LAST_MOD_DTTM, SOURCE, CMPLX_NUM, LIVING_GBA, FULLADDRESS, CITY, STATE, ZIPCODE, NATIONALGRID, LATITUDE, LONGITUDE, ASSESSMENT_NBHD, ASSESSMENT_SUBNBHD, CENSUS_TRACT, CENSUS_BLOCK, WARD, SQUARE, X, Y, QUADRANT]
Index: []

[0 rows x 49 columns]

In [36]:
# How many missing values do we have ?
df.isnull().sum()

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64

In [45]:
df.describe()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646

In [41]:
# Average Housing Price
df['PRICE'].mean()

931351.5949336156

In [42]:
# Min Housing Price
df['PRICE'].min()

1.0

In [43]:
# The more frequent price (mode)
df['PRICE'].mode()

0    350000.0
dtype: float64

In [47]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [54]:
# Average Price and Number of rooms per condition

df[['PRICE','ROOMS']].groupby(df['CNDTN']).mean()

                  PRICE     ROOMS
CNDTN
Average    3.755836e+05  7.121648
Default    8.518500e+06  0.315789
Excellent  1.247995e+06  8.652466
Fair       4.093604e+05  7.260606
Good       6.551493e+05  7.586474
Poor       4.742626e+05  6.977143
Very Good  9.455850e+05  8.143419

In [55]:
# Average Price and quantity of rooms per source

df[['PRICE','ROOMS']].groupby(df['SOURCE']).mean()

                    PRICE     ROOMS
SOURCE
Condominium  1.436073e+06  3.748857
Residential  5.799119e+05  7.382329

In [58]:
pd.pivot_table(df,index=['ROOMS','CNDTN','SOURCE'],values=['PRICE'],aggfunc='mean')

                                    PRICE
ROOMS CNDTN     SOURCE
0     Average   Residential  2.493296e+05
      Default   Residential  1.119167e+07
      Fair      Residential  9.893333e+05
      Good      Residential  2.950000e+05
      Poor      Residential  2.968510e+06
      Very Good Residential           NaN
1     Average   Residential           NaN
      Default   Residential           NaN
      Fair      Residential  5.613000e+04
      Good      Residential           NaN
2     Average   Residential  2.339993e+05
      Fair      Residential           NaN
      Good      Residential  1.055500e+06
      Poor      Residential           NaN
3     Average   Residential  2.393207e+05
      Excellent Residential           NaN
      Fair      Residential  5.674600e+05
      Good      Residential  5.109397e+05
      Very Good Residential  5.290000e+05
4     Average   Residential  2.781585e+05
      Excellent Residential  6.800000e+05
      Fair      Residential  2.849881e+05
      Good      Residential  4.574770e+05
      Poor      Residential  1.600857e+05
      Very Good Residential  7.328964e+05
5     Average   Residential  2.549263e+05
      Default   Residential  4.990000e+05
      Excellent Residential  1.151971e+06
      Fair      Residential  2.354260e+05
      Good      Residential  4.425910e+05
...                                   ...
22    Good      Residential  1.307000e+06
      Very Good Residential  4.925000e+06
23    Average   Residential  1.178140e+06
      Excellent Residential           NaN
      Good      Residential  2.083333e+06
      Very Good Residential           NaN
24    Average   Residential  2.655817e+05
      Good      Residential           NaN
      Very Good Residential  2.500000e+05
25    Average   Residential           NaN
      Excellent Residential  1.800000e+07
      Good      Residential  5.400000e+05
      Very Good Residential  8.450000e+06
26    Excellent Residential  1.500000e+07
27    Excellent Residential           NaN
      Very Good Residential           NaN
28    Average   Residential  6.985000e+05
      Good      Residential  7.785000e+06
29    Good      Residential           NaN
30    Average   Residential  2.000000e+05
31    Very Good Residential  2.396029e+07
32    Very Good Residential           NaN
34    Very Good Residential           NaN
35    Good      Residential           NaN
37    Excellent Residential           NaN
39    Excellent Residential           NaN
      Very Good Residential           NaN
40    Very Good Residential           NaN
41    Excellent Residential           NaN
48    Excellent Residential           NaN

[153 rows x 1 columns]